version: "3.3"
services:
    backend:
        build:
            context: ./
            dockerfile: ./Dockerfile.backend
            args:
                - TYPEORM_CONNECTION=$TYPEORM_CONNECTION
                - TYPEORM_ENTITIES=$TYPEORM_ENTITIES
                - TYPEORM_HOST=$TYPEORM_HOST 
                - TYPEORM_PORT=5432
                - TYPEORM_USERNAME=$TYPEORM_USERNAME
                - TYPEORM_PASSWORD=$TYPEORM_PASSWORD
                - TYPEORM_DATABASE=$TYPEORM_DATABASE
                - TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS 
                - TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR
        image: backend:latest
        container_name: capstone_backend
        environment:
            - TYPEORM_CONNECTION 
            - TYPEORM_ENTITIES 
            - TYPEORM_HOST 
            - TYPEORM_USERNAME
            - TYPEORM_PASSWORD
            - TYPEORM_DATABASE
            - TYPEORM_MIGRATIONS 
            - TYPEORM_MIGRATIONS_DIR
        tty: true
        restart: always
        ports:
            - 3030:3030